learnscout/learnscout/models.py
from learnscout import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(25), unique=True, nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    function_selected = db.Column(db.String(100), nullable=False, default="TBD")

    def __repr__(self):
        return f"('{self.username}', '{self.email}', '{self.function_selected}')"

class Function(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    functionname = db.Column(db.String(100), unique=True, nullable=False)
    skill_1 = db.Column(db.String(100), nullable=True)
    skill_2 = db.Column(db.String(100), nullable=True)
    skill_3 = db.Column(db.String(100), nullable=True)

    def __repr__(self):
        return f"Function('{self.functionname}', '{self.skill_1}', '{self.skill_2}' , '{self.skill_3}')"

class Training(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    trainingname = db.Column(db.String(100), unique=True, nullable=False)
    signed_up = db.Column(db.String(25), nullable=True)
    participant = db.Column(db.String(25), nullable=True)
    material = db.Column(db.String(200), unique=True, nullable=True)

    def __repr__(self):
        return f"Training('{self.trainingname}', '{self.signed_up}', '{self.participant}')"

learnscout/learnscout/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from learnscout.models import User



class RegistrationForm(FlaskForm):
    username = StringField('Your name', validators=[DataRequired(),Length(min=2, max=25)])
    email = StringField('Your email', validators=[DataRequired(), Email()])
    password = PasswordField('Your password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm your password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('Username exists already. Please choose a different one.')
    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Email exists already. Please choose a different one.')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember me')
    submit = SubmitField('Login')

learnscout/learnscout/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user #under construction
from learnscout.models import User

class RegistrationForm(FlaskForm):
    username = StringField('Your name', validators=[DataRequired(),Length(min=2, max=25)])
    email = StringField('Your email', validators=[DataRequired(), Email()])
    password = PasswordField('Your password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm your password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('Username exists already. Please choose a different one.')
    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Email exists already. Please choose a different one.')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember me')
    submit = SubmitField('Login')

learnscout/learnscout/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from learnscout.config import Config 


db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view ='users.login'

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    from learnscout.users.routes import users 
    from learnscout.trainings.routes import trainings 
    #from learnscout.functions.routes import functions 
    from learnscout.main.routes import main 
    app.register_blueprint(users)
    app.register_blueprint(trainings)
    #app.register_blueprint(functions)
    app.register_blueprint(main)

    return app

learnscout/learnscout/main/routes.py
from flask import render_template, Blueprint 

main = Blueprint('main', __name__)

@main.route('/' ,)
@main.route('/welcome',)
@main.route('/learnscout',)
@main.route('/logout' ,)
def welcome():
    return render_template('welcome.html', title='Welcome')

learnscout/learnscout/trainings/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint
from flask_login import login_user, current_user #under construction
from learnscout import db #under construction
from learnscout.models import User, Function, Training #under construction
from learnscout.users.forms import LoginForm
from learnscout.trainings import db_connect_dropdown as dropdown, db_connect_traininglist as traininglist

trainings = Blueprint('trainings', __name__)

@trainings.route('/getguidance' , methods=['GET', 'POST'])
def getguidance():
    form=LoginForm()
    return render_template('getguidance.html', title='Get Guidance', form=form, functions=dropdown.get_data(), training=traininglist.get_training())

def update_function():
    form=LoginForm()
    if form.validate_on_submit():
        newfunction = request.form.get("selected_function")
        oldfunction = request.form.get("empty_function")
        update = User.query.filter_by(username=current_user.username).first()
        update.function_selected = newfunction
        db.session.commit()
        location.reload
    return render_template('myupskillingplan.html', title='Get Guidance', form=form, functions=dropdown.get_data(), training=traininglist.get_training())

@trainings.route('/myupskillingplan')
def myupskillingplan():
    return render_template('myupskillingplan.html', title='My Upskilling Plan')

@trainings.route('/startupskilling')
def startupskilling():
    return render_template('startupskilling.html', title='Start Upskilling')

@trainings.route('/material')
def material():
    return render_template('material.html', title='Material for Upskilling')

learnscout/learnscout/users/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint
from flask_login import login_user, current_user
from learnscout import db, bcrypt
from learnscout.models import User, Function, Training 
from learnscout.users.forms import RegistrationForm, LoginForm 

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form=RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username = form.username.data, email = form.email.data, password = hashed_password )
        db.session.add(user)
        db.session.commit()
        flash(f"Thank you, {form.username.data.title()}. Your account has been created successfully,  . . .")
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    form=LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash (f", your login was successful.")
            return redirect(url_for('trainings.getguidance'))

        else:
            flash ("Login not successful. Please check you email and password.")
    return render_template('login.html', title='Login', form=form)




learnscout/learnscout/templates/getguidance.html
{% extends "layout.html" %}
{% block content %}

<div class="item-heading-left">
  <h1>Get Guidance.</h1>
</div>
<div class="item-alert-middle">
  {% with messages = get_flashed_messages() %}
  {% if messages %}
  {% for message in messages %}
  <h3>{{ current_user.username.title()}} {{message }}</h3>
  {% endfor %}
  {% endif %}
  {% endwith %}
</div>
<div class="item-explain-left">
  <p>We asked your line manager to recommed upskilling content. The result you find here: training material that is tailormade for you and as relevant as possible for your daily job and your long-term personal development. <br><br>By this LEARNSCOUT makes your investment into your upskilling worth every minute. <br><br>Enjoy your development with LEARNSCOUT, {{ current_user.username.title()}}.
  </p>
</div>
{% if current_user.function_selected == "TBD" %}

<div class="item-explain-right">
  <form method="POST" action='/getguidance'>
    <input type="hidden" value="TBD" name="empty_function">
    <label><p>Select your function please: (WIP)</p>
      <select class="custom_select" id="option_selected">
        <option><p>I am working in . . . </p></option>
        {% for x in functions %}
        <option value="{{x}}"><p>{{ x }}</p></option>
        {% endfor %}
      </select>
    </label>
    </div>
    <div class="item-go-r">
      <a type="submit" class="go-img" href={{ url_for('trainings.myupskillingplan') }}>
          <img src={{ url_for('static', filename='play_icon.png' ) }} alt="Link to upskilling plan" width=50px height=50px>
      </a>
  </form>
    </div>

{% else %}
<div class="item-explain-right">
  <p>You told us that your are working in the {{ current_user.function_selected.title()}}-function.
  Based on that LEARNSCOUT recommends the following trainings that are tailormade for you, {{ current_user.username.title()}}: <br><br>
  Please select the training you are interested in most:</p>
</div>
<div class="item-info-right">
  <form action='/myupskillingplan'>
    {% for x in training %}
    <p>
    <label class="label">
      <input type="radio" name="radio" class="radio">
      <span class="checkmark"></span>
      {{ x }}
      <br>
    </label>
    </p>
    {% endfor %}


</div>
<div class="item-go-r">
  <input type="submit" value="WIP" class="button">

</form>
</div>
{% endif %}
{% endblock content %}

learnscout/learnscout/templates/layout.html
{% extends "layout_basic.html" %}
{% block layout %}
<div class="outer-h">
  <header>
    <div class="container-index-h">
      <div class="item-logo">
        <div class="logo-img">
        </div>
      </div>
      <div class="nav" id="navBar">
        <a href={{ url_for('trainings.getguidance') }}>get guidance</a>
        <a href={{ url_for('trainings.myupskillingplan') }}>my upskilling</a>
        <a href={{ url_for('main.welcome') }}>logout</a>
        <a href="javascript:void(0);" class="icon" onclick="responsive_NavBar()">&#9776;</a>
      </div>
    </div>
  </header>
</div>
<main>
  <div class="outer-m">
    <div class="container-index-m">

      {% block content %}{% endblock %}

    </div>
  </div>
</main>
{% endblock layout %}

learnscout/learnscout/templates/layout_basic.html
<!DOCTYPE html>
<html lang="en-US">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description"="learn scout offers training content for employees tailormade for their roles and    proficiency level ">

  {% if title %}
  <title>learnscout - {{ title }}</title>
  {% else %}
  <title>learnscout</title>
  {% endif %}

  <link rel="stylesheet" href="static/styles/main.css">
  <link rel="icon" sizes="32x32" type="image/x-icon" href={{ url_for('static', filename='favicon.ico' ) }}>
  <link rel="stylesheet" href="static/styles/Rajdhani-Regular.ttf">
  <link rel="stylesheet" href="static/styles/Roboto-Regular.ttf">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body>
  <div class="bg-img main" style="background-image: url(/static/background_blank.jpg)">

    {% block layout %}{% endblock %}

  </div>
  <script src="static/scripts.js"></script>
</body>

</html>

learnscout/learnscout/templates/login.html
{% extends "layout_basic.html" %}
{% block layout %}
<div class="outer-none">
  <header>
    <div class="container-index-h">
      <div class="item-logo">
        <div class="logo-img">
        </div>
      </div>
      <div class="item-alert-nav">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <h3>{{ message }}</h3>
        {% endfor %}
        {% endif %}
        {% endwith %}
      </div>
    </div>
  </header>
  <main>
    <div class="container-index-m">
      <div class="item-go-t">
        <a class="button-img" href={{ url_for('main.welcome') }}>
          <img src={{ url_for('static', filename='back_icon.png' ) }} alt="Link to Welcome" width=50px height=50px>
        </a>
      </div>
      <div class="item-heading-login">
        <h1>Please log in.</h1>
      </div>
      <div class="item-explain-login">
        <p>Log in with your email-address and your password. New to learn scout? <a href={{ url_for('users.register')}}>Register here</a></p>
      </div>
      <div class="item-info-login">
        <div class="content-sction">
          <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
              <div class="form-group">
                {{ form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is invalid")}}
                <div class="invalid_feedback">
                  {% for error in form.email.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg")}}
                {% endif %}
              </div>
              <div class="form-group">
                {{ form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is invalid")}}
                <div class="invalid_feedback">
                  {% for error in form.password.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control")}}
                {% endif %}
              </div>
              <div class="form-check">
                {{ form.remember(class="form-check-input")}}
                {{ form.remember.label(class="form-check-label")}}
              </div>
            </fieldset>
            <div z-index="1">
              {{ form.submit(class="button")}}
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
</div>
{% endblock layout %}

learnscout/learnscout/templates/material.html
{% extends "layout.html" %}
{% block content %}
    <div class="item-heading-left">
        <h1>Trainingsmaterial for you</h1>
    </div>
    <div class="item-explain-left"> 
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat voluptates expedita rem dolorem, molest sit amet consectetur adipisicing elit. Placeat voluptates expedita rem dolorem, molest
        </p>
    </div>
    <div class="item-info-left">
        <section>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat voluptateicing elit. Placeat voluptates expedita rem dolorem, molestias quas natus deleniti necessitatibus nesciunt volupta nesciunt voluptatem iure ns expedita rem dolorem, molestias quas natus deleniti necessitatibus nesciunt voluptatem iure nemo dolor at.
        </section>
    </div>
    <div class="item-explain-right"> 
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat voluptates expedita rem dolor.
        </p>
    </div>
    <div class="item-info-right">
        <section>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat voluptates expedita rem dolorem, molestias quas natus deleniti necessitatibus nesciunt voluptatem iure nemo dolor at.
        </section>
    </div>
    <div class="item-go-r">
        <a class="button-img" href={{ url_for('users.login') }}>
            <img src={{ url_for('static', filename='play_icon.png' ) }} alt="Link to login" width=50px height=50px>
        </a>
    </div>
{% endblock content %}

learnscout/learnscout/templates/myupskillingplan.html
{% extends "layout.html" %}
{% block content %}
    <div class="item-heading-left">
        <h1>My Upskilling Plan</h1>
    </div>
    <div class="item-explain-left">
        <p>You already took the first important step: you decided to start your upskilling now. So don’t waist time and click the button and get future-fit.
        </p>
    </div>
    <div class="item-info-left">
        <section>Work in progress
    </div>
    
{% endblock content %}

learnscout/learnscout/templates/register.html
{% extends "layout_basic.html" %}
{% block layout %}
<div class="outer-none">
  <header>
    <div class="container-index-h">
      <div class="item-logo">
        <div class="logo-img">
        </div>
      </div>
    </div>
  </header>
  <main>
    <div class="container-index-m">
      <div class="item-go-t">
        <a class="button-img" href={{ url_for('main.welcome') }}>
          <img src={{ url_for('static', filename='back_icon.png' ) }} alt="Link to Welcome" width=50px height=50px>
        </a>
      </div>
      <div class="item-heading-regi">
        <h1>Please register</h1>
      </div>
      <div class="item-explain-regi">
        <p>Already registered? <a href={{ url_for('users.login')}}>Login here</a></p>
      </div>
      <div class="item-info-regi">
        <div class="content-sction">
          <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
              <div class="form-group">
                {{ form.username.label(class="form-control-label")}}
                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is invalid")}}
                <div class="invalid_feedback">
                  {% for error in form.username.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg")}}
                {% endif %}
              </div>
              <div class="form-group">
                {{ form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is invalid")}}
                <div class="invalid_feedback">
                  {% for error in form.email.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg")}}
                {% endif %}
              </div>
              <div class="form-group">
                {{ form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is invalid")}}
                <div class="invalid_feedback">
                  {% for error in form.password.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control")}}
                {% endif %}
              </div>
              <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label")}}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is invalid")}}
                <div class="invalid_feedback">
                  {% for error in form.confirm_password.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control")}}
                {% endif %}
              </div>
            </fieldset>

            <div class="form-group" z-index="1">
              {{ form.submit(class="button")}}
            </div>
            <div class="form-group">
              <footer class="item-footer" onclick="openFrame()">* by clicking Sign up, you agree to our Terms.
              </footer>
            </div>
          </form>
        </div>
      </div>
      <!-- T&C page - Client-Side rendered with JS-->
      <div>
        <aside class="frame" id="conditions">
          <div class="item-heading-regi">
            <h2>Please read our Terms & Conditions carefully.</h2>
          </div>
          <h6>Some things in life are bad, <br> They can really make you mad.<br>
            Other things just make you swear and curse.<br> When you're chewing on life's gristle, <br>Don't grumble, give a whistle!<br>
            And this'll help things turn out for the best <br>And <br>
            Always look on the bright side of life! </h6>
          <button class="agree-button" onclick=closeFrame()> agree </button>
        </aside>
      </div>

  </main>
</div>
{% endblock layout %}

learnscout/learnscout/templates/startupskilling.html
{% extends "layout.html" %}
{% block content %}
    <div class="item-heading-left">
        <h1>Start your Upskilling now</h1>
    </div>
    <div class="item-explain-left"> 
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat voluptates expedita rem dolorem, molest sit amet consectetur adipisicing elit. Placeat voluptates expedita rem dolorem, molest
        </p>
    </div>
    <div class="item-info-left">
        <section>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat voluptateicing elit. Placeat voluptates expedita rem dolorem, molestias quas natus deleniti necessitatibus nesciunt volupta nesciunt voluptatem iure ns expedita rem dolorem, molestias quas natus deleniti necessitatibus nesciunt voluptatem iure nemo dolor at.
        </section>
    </div>
    <div class="item-explain-right"> 
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat voluptates expedita rem dolor.
        </p>
    </div>
    <div class="item-info-right">
        <section>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat voluptates expedita rem dolorem, molestias quas natus deleniti necessitatibus nesciunt voluptatem iure nemo dolor at.
        </section>
    </div>
    <div class="item-go-r">
        <a class="button-img" href={{ url_for('users.login') }}>
            <img src={{ url_for('static', filename='play_icon.png' ) }} alt="Link to login" width=50px height=50px>
        </a>
    </div>
{% endblock content %}

learnscout/learnscout/templates/welcome.html
{% extends "layout_basic.html" %}
{% block layout %}
<div class="bg-img" style="background-image: url(/static/background_way.jpg);">
  <header>
    <div class="container-index-h">
      <div class="item-logo">
        <div class="logo-img">
        </div>
      </div>
    </div>
  </header>
  <main>
    <div class="container-index-m">
      <div class="item-heading-right">
        <h1>guided upskilling:<br>tailormade<br>for you</h1>
      </div>
      <div class="item-start">
        <a class="go-img" href={{ url_for('users.login') }}>
          <img src={{ url_for('static', filename='play_icon.png' ) }} alt="Link to login" width=50px height=50px>
        </a>
      </div>
    </div>
  </main>
</div>
{% endblock layout %}